baseURL: https://blachniet.github.io/
languageCode: en-us
title: Brian Lachniet
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
      - name: Archive
        url: archives
        weight: 5
      - name: Search
        url: search/
        weight: 10
      - name: Tags
        url: tags/
        weight: 10

outputs:
  home:
  - HTML
  - RSS
  - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Brian Lachniet - https://blachniet.github.io/"
  # Don't set author since everything on this site is by me.
  # author: Brian Lachniet

  defaultTheme: auto
  # disableThemeToggle: false
  ShowShareButtons: true
  ShowReadingTime: false
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true  # Previous/next buttons at bottom of posts.
  ShowBreadCrumbs: false  # Breadcrumbs are overkill for this site.
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: false  # Toc at the top of posts is overkill.
  comments: false  # I don't support comments on this site.
  # TODO Add an image to be used for sharing. https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/#enhanced-seo
  images: ["papermod-cover.png"]

  profileMode:
    enabled: true
    title: Hi, I'm Brian Lachniet
    subtitle: |
      I’m a Christian, husband, father and software engineer.
    # TODO: Replace gravatar URL
    imageUrl: "https://en.gravatar.com/userimage/25295429/748d5381c94f3b7fd04db4e1670fd381.jpg?size=200"
    imageTitle: Brian Lachniet
    # imageWidth: 120
    # imageHeight: 120
    buttons:
    - name: Archives
      url: archives
    - name: Tags
      url: tags

  homeInfoParams:
    Title: "Hi, I'm Brian Lachniet"
    # TODO: Update homeInfoParams.Content
    Content: |
      I’m a Christian, husband, father and software engineer.

      If you’d like to learn more about my professional experience, check out
      my [LinkedIn profile](https://www.linkedin.com/in/blachniet/).

  # See all social icons at
  # https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-icons/
  socialIcons:
  - name: github
    url: "https://github.com/blachniet"
  - name: linkedin
    url: "https://www.linkedin.com/in/blachniet/"
  - name: twitter
    url: "https://twitter.com/blachniet"
  - name: keybase
    url: "https://keybase.io/blachniet"
  - name: cv
    url: "https://docs.google.com/document/d/1alOhCXFduDbV_m8P5PAhnR3GEnBWWJauUXsMqsyLwFE"
  - name: rss
    url: "/index.xml"

  editPost:
    URL: "https://github.com/blachniet/blachniet.github.io/edit/master/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # label:
  #   text: "Home"
  #   icon: icon.png
  #   iconHeight: 35

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"

  # TODO: Add favicons
  assets:
    disableHLJS: true
  #   favicon: "<link / abs url>"
  #   favicon16x16: "<link / abs url>"
  #   favicon32x32: "<link / abs url>"
  #   apple_touch_icon: "<link / abs url>"
  #   safari_pinned_tab: "<link / abs url>"

  # cover:
  #   hidden: true # hide everywhere but not in structured data
  #   hiddenInList: true # hide on list pages and home
  #   hiddenInSingle: true # hide on single page

  # fuseOpts:
  #   isCaseSensitive: false
  #   shouldSort: true
  #   location: 0
  #   distance: 1000
  #   threshold: 0.4
  #   minMatchCharLength: 0
  #   keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
